# Workflow 1
name: "Commit Testing"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout specific commit
      uses: actions/checkout@v2
      with:
        ref: f3275faa4c5fb512583a7cfd65348904f047c01a
  
    - name: Testing
      run: |
        ls -al
        cat  .github/workflows/commit.yml
        pwd

        git log --pretty --oneline

