
name: POC | MCK
on:
on:      
  workflow_dispatch:
    inputs:
      restart-controllers:
        type: boolean
        required: true
        default: false

jobs:
  First_Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running Commands
      run: |
        ls -al
        pwd

