# Workflow 1
name: Workflow1
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set variable
      run: ech "DB_UPDATE=LMDA" >> $GITHUB_ENV
    
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: $GITHUB_ENV
  
  post_fail:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Call Another Workflow
      if: ${{ needs.build.result == 'failure' }}
      run: |
        # gh workflow run two.yml -f greeting=hello
        gh api \
        --method PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/mehulsharma2010/mvn-project/actions/variables/NAME \
        -f name='TEST' \
        -f value='octocat'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_success:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Call Another Workflow
      if: ${{ needs.build.result == 'failure' }}
      run: |
        echo "Job success"
