# Workflow 1
name: Workflow1
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set variable
      run: ech "DB_UPDATE=LMDA" >> $GITHUB_ENV
    
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: $GITHUB_ENV
  
  post_fail:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Call Another Workflow
      if: ${{ needs.build.result == 'failure' }}
      run: |
        gh workflow run two.yml -f name=Workflow2 -f greeting=hello
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
