name: "Rollback Workflow"

on:  
  workflow_dispatch:
    inputs:
      release-version:
        description: 'TAG_NUMBER'
        required: true
        default: "lynx-releases-6.14.1-2023-12-04-080835-581"
    
  repository_dispatch:
    types: [if_failure]
    
env:
  TAG_NUMBER: "${{ github.event.inputs.release-version }}"

jobs:
    rollback:
      name: "Rollback"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Rollback
          run: |
            echo "Rollback"
            echo ${{ env.TAG_NUMBER }}