# Workflow 2
name: Workflow2
on:
  workflow_run:
    workflows: ["Workflow1"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: Use variable
      run: echo "Variable value is ${{ env.DB_UPDATE }}"