# Workflow 2
name: Workflow2
on: 
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Test'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  greeting: ${{ github.event.inputs.greeting }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use variable
      run: |
        echo "Variable value is ${{ env.greeting }}"
        echo "Variable value is $greeting"
